### ISSUE TITLE
About/Who we are Page - Seems to have different style

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack-www#115]
![Screenshot 2023-05-10 at 12 35 15](https://github.com/apache/cloudstack-www/assets/13551960/dd36cdf5-9056-4dc2-9dbd-335e883ad976)
I'm not sure about the blue frame (if it needs to be present or not), but the Font of the text is different from the rest of the pages, is this on purpose? 
For example the community bylaws, which is same as any other page
![Screenshot 2023-05-10 at 12 36 32](https://github.com/apache/cloudstack-www/assets/13551960/9d3f516a-49d1-4b8d-a9b1-d4dfae323bed)

**Comment by rohityadavcloud** [comment]
@borisstoyanov it's because the who page embed the page from ASF. I couldn't figure out how to fetch the information like the old website, and instead the iframe was used: https://github.com/apache/cloudstack-www/blob/docusaurus-staging/src/pages/who.md?plain=1

Of course, we should be able to figure this out and fix it.

**Comment by rohityadavcloud** [comment]
Fixed it with manual lists that is similar to the one we've. Closing this.

**Comment by borisstoyanov** [comment]
Thanks @rohityadavcloud
